// What a card's effects do, by family: every method of the scripts' effect context (EffectContext in
// packages/core/src/engine/effects/context.ts, called as fx.<method>) belongs to exactly one family; "none" is plumbing
// (choices, reveals, the context's own properties). The card feature table counts a card's call sites per family. A method
// missing here fails the table's test, so a new effect gets a family (or "none") when it is added.
export const FX_FAMILIES = {
  dmg: ["dealDamage", "dealDamages", "dealDividedDamage"],
  aoe: ["dealDamageEach"],
  destroy: ["destroy"],
  banish: ["banish"],
  toHand: ["returnToHand"],
  stats: ["dealsMoreDamage", "giveStats"],
  keyword: ["gainText", "giveDrive", "giveKeyword"],
  heal: ["giveLeaderDefense"],
  draw: ["draw"],
  search: ["lookAt", "search", "searchEach", "topCards"],
  summon: ["fromEvolveDeck", "putOntoField", "summon"],
  ex: ["putIntoEx", "tokensToEx", "topToEx"],
  discard: ["discard", "discardCards", "discardHand", "discardRandom"],
  mill: ["mill"],
  bury: ["bury"],
  pp: ["increaseMaxPlayPoints", "payPlayPoints", "recoverPlayPoints"],
  cost: ["cardsCostLessThisTurn", "changePlayCost", "nextPlayCostsLess", "setPlayCost"],
  counters: ["addCounters", "addToStack", "payEarthRite", "removeCounters"],
  evolve: ["changeEvolveCost", "evolve", "gainEvolutionPoints", "setEvolveCost", "turnFacedown", "turnFaceup"],
  engage: ["engage"],
  refresh: ["refresh"],
  protect: ["capDamage", "preventDamage", "preventNextDamage", "reduceDamage", "reduceNextDamage"],
  restrict: ["blockFanfare", "box", "cannotAttack", "cannotAttackLeader", "cannotDealDamage", "cantActivate", "loseAbilities", "restrictPlayer", "skipNextRefresh"],
  deck: ["bottomInAnyOrder", "putIntoDeckAt", "putOnDeck", "putOnDeckInAnyOrder", "shuffleDeck", "shuffleToBottom"],
  // grant: most granted abilities are end-of-turn drawbacks or parts of a removal, not ability gains.
  other: [
    "allowPlayFromBanishedThisTurn",
    "changeType",
    "driveCheck",
    "equip",
    "executeUnionBurst",
    "extraTurn",
    "fuse",
    "giveControl",
    "giveTrait",
    "grant",
    "maneuver",
    "playCard",
    "race",
    "ride",
    "rollDie",
    "serve",
    "setLeaderDefense",
    "skipNextTurn",
    "steal",
    "transform",
    "winGame",
  ],
  none: [
    "choose",
    "chooseCards",
    "confirm",
    "controller",
    "data",
    "declareCardName",
    "delay",
    "earthRitePaid",
    "event",
    "game",
    "memory",
    "mode",
    "optionalCost",
    "playOption",
    "randomCards",
    "recordUse",
    "reveal",
    "selectCards",
    "self",
    "sourceDef",
    "targets",
  ],
} as const;

export type FxFamily = Exclude<keyof typeof FX_FAMILIES, "none">;
export const FX_FAMILY_NAMES = Object.keys(FX_FAMILIES).filter((f) => f !== "none") as FxFamily[];
export const FAMILY_OF: ReadonlyMap<string, keyof typeof FX_FAMILIES> = new Map(
  Object.entries(FX_FAMILIES).flatMap(([family, methods]) => methods.map((m) => [m, family as keyof typeof FX_FAMILIES] as const)),
);
