// Generated by `npm run scripts:index` — do not edit.
import type { ScriptRegistry } from "../types";

/**
 * Card scripts of DIY01, keyed by canonical definition id (alternate printings resolve to the
 * canonical id through the card database). Cards without card text need no script.
 */
export const DIY01_SCRIPTS: ScriptRegistry = {
};
