import data from "../../data/DIY01.json" with { type: "json" };
import { readCardSetFile } from "../data/set-file";
import type { CardDefinition } from "../model/card";
import { DIY01_SCRIPTS } from "../script/DIY01";

/**
 * DIY01 card definitions (generated by `npm run build:cards` from data/custom.ts): community-made cards. Its alternate
 * arts join the earlier sets' tokens; its own definitions are new leaders.
 */
export const DIY01_CARDS: readonly CardDefinition[] = readCardSetFile(data).cards;

export { DIY01_SCRIPTS };
